version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_project
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: >
      sh -c "composer install &&
             php artisan serve --host=0.0.0.0 --port=8000"
